name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_for_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 11
    - name: Install dependencies
      run: yarn install
    - name: Compile
      run: yarn compile
    - name: Build
      run: yarn dist
    - uses: actions/upload-artifact@master
      with:
        name: dist-mac
        path: dist
    - name: release
      env:
        AID: ${{ secrets.AID }}
        AIP: ${{ secrets.AIP }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        GH_TOKEN: ${{ secrets.GH_ITUOB_CI_TOKEN }}
      run: yarn release

  build_for_windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 11
    - name: install node tools
      run: npm install --global --production windows-build-tools@4.0.0
    - name: install node-gyp
      run: npm install --global node-gyp@latest
    - name: Set node config to use python2.7
      run: npm config set python python2.7
    - name: Set node config to set msvs_version to 2015
      run: npm config set msvs_version 2015
    - name: Install dependencies
      run: yarn install
    - name: Compile
      run: yarn compile
    - name: Build
      run: yarn dist
    - uses: actions/upload-artifact@master
      with:
        name: dist-windows
        path: dist
    - name: release
      env:
        GH_TOKEN: ${{ secrets.GH_ITUOB_CI_TOKEN }}
      run: yarn release

